---
- name: Create app dir
  become: yes
  file:
    path: /home/ubuntu/app
    state: directory

- name: "Copy backend build folder to EC2"
  become: yes
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/app/
    owner: ubuntu

- name: "NPM Install"
  shell: |
    sudo apt update
    sudo apt-get install -y npm
    cd /home/ubuntu/app

- name: "Start backend with pm2"
  become: yes
  shell: |
    cd /home/ubuntu/app
    npm run start
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"